In [1]:
%pip install "gymnasium[atari, accept-rom-license]"

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import torch
import numpy as np
import gymnasium as gym

env_name = 'ALE/Assault-ram-v5'
env = gym.make(env_name)

print(env.observation_space.shape)
y = 1
for x in env.observation_space.shape:
    y = y * x
print(y)

initial_state,info = env.reset()

print(initial_state)
print(info)

(210, 160, 3)
100800
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
{'lives': 4, 'episode_frame_number': 0, 'frame_number': 0}


In [ ]:
rand = np.random.rand() 


observation_prime, reward, terminated, truncated, info = env.step(2)

print(observation_prime)

TypeError: list indices must be integers or slices, not list